engines:
  checkstyle:
    enabled: true
    channel: "beta"
  pmd:
    enabled: true
    channel: "beta"

exclude_paths:
  - integration-test/
  - tools/
  - vagrant/

ratings:
  paths:
  - "**.java"
